# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='autor', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(default='', upload_to='user_media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=320),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2015),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='description', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
